#
# $FreeBSD: head/en_US.ISO8859-1/articles/portbuild/Makefile 38826 2012-05-17 19:12:14Z hrs $
#
# Article: Portbuild Procedure
#

DOC?= article

NO_TIDY=YES

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
